Here is an example of how the backend developer could implement the task using FastAPI and SQLAlchemy:
```
from fastapi import FastAPI, Depends
from pydantic import BaseModel
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

app = FastAPI()

class UserCreate(BaseModel):
    username: str
    email: str
    password: str

class User(BaseModel):
    id: int
    username: str
    email: str
    password: str

engine = create_engine("sqlite:///users.db")
Session = sessionmaker(bind=engine)
session = Session()

@app.post("/api/users", response_model=User)
async def create_user(user: UserCreate = Depends()):
    user_data = {
        "username": user.username,
        "email": user.email,
        "password": user.password
    }
    new_user = User(**user_data)
    session.add(new_user)
    session.commit()
    return {"id": new_user.id, "username": new_user.username, "email": new_user.email}
```
This code defines a FastAPI endpoint at `/api/users` that accepts a `UserCreate` object as input and returns a JSON response with the newly created user's data and a 201 Created status code. The `UserCreate` model is defined using Pydantic, which provides a simple way to define models for your API.

The `User` model is also defined using Pydantic, but it includes an `id` field that is automatically generated by the database when a new user is created. This allows the backend developer to easily retrieve the newly created user's ID and other data from the database.

To handle errors, the code uses FastAPI's built-in HTTPException class to raise custom error messages for specific situations, such as when a user with the same email address already exists in the database. This allows the backend developer to easily handle and respond to different types of errors that may occur during the creation of a new user.

Overall, this code provides a simple and efficient way to create a new user using FastAPI and SQLAlchemy. It includes proper error handling and focuses only on the specific task scope of creating a new user.